graph TD
    starry_v0_1_0[starry v0.1.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    axdriver_v0_2_0[axdriver v0.2.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    axalloc_v0_2_0[axalloc v0.2.0] --> allocator_v0_1_2[allocator v0.1.2]
    allocator_v0_1_2[allocator v0.1.2] --> axerrno_v0_1_2[axerrno v0.1.2]
    axerrno_v0_1_2[axerrno v0.1.2] --> axerrno_v0_2_2[axerrno v0.2.2]
    axerrno_v0_2_2[axerrno v0.2.2] --> heck_v0_5_0[heck v0.5.0]
    axerrno_v0_2_2[axerrno v0.2.2] --> unicode_ident_v1_0_22[unicode-ident v1.0.22]
    allocator_v0_1_2[allocator v0.1.2] --> bitmap_allocator_v0_2_1[bitmap-allocator v0.2.1]
    bitmap_allocator_v0_2_1[bitmap-allocator v0.2.1] --> bit_field_v0_10_3[bit_field v0.10.3]
    allocator_v0_1_2[allocator v0.1.2] --> rlsf_v0_2_1[rlsf v0.2.1]
    rlsf_v0_2_1[rlsf v0.2.1] --> base64_v0_13_1[base64 v0.13.1]
    rlsf_v0_2_1[rlsf v0.2.1] --> unicode_ident_v1_0_22[unicode-ident v1.0.22]
    rlsf_v0_2_1[rlsf v0.2.1] --> unicode_width_v0_1_14[unicode-width v0.1.14]
    allocator_v0_1_2[allocator v0.1.2] --> slab_allocator_v0_3_1[slab_allocator v0.3.1]
    slab_allocator_v0_3_1[slab_allocator v0.3.1] --> buddy_system_allocator_v0_10_0[buddy_system_allocator v0.10.0]
    axalloc_v0_2_0[axalloc v0.2.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    axalloc_v0_2_0[axalloc v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    kspin_v0_1_1[kspin v0.1.1] --> kernel_guard_v0_1_3[kernel_guard v0.1.3]
    kernel_guard_v0_1_3[kernel_guard v0.1.3] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axalloc_v0_2_0[axalloc v0.2.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axdriver_v0_2_0[axdriver v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axconfig_v0_2_0[axconfig v0.2.0] --> axconfig_macros_v0_2_0[axconfig-macros v0.2.0]
    axconfig_macros_v0_2_0[axconfig-macros v0.2.0] --> axconfig_gen_v0_2_0[axconfig-gen v0.2.0]
    axconfig_gen_v0_2_0[axconfig-gen v0.2.0] --> clap_builder_v4_5_53[clap_builder v4.5.53]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> anstyle_v1_0_13[anstyle v1.0.13]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> anstyle_parse_v0_2_7[anstyle-parse v0.2.7]
    anstyle_parse_v0_2_7[anstyle-parse v0.2.7] --> utf8parse_v0_2_2[utf8parse v0.2.2]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> anstyle_query_v1_1_5[anstyle-query v1.1.5]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> colorchoice_v1_0_4[colorchoice v1.0.4]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> is_terminal_polyfill_v1_70_2[is_terminal_polyfill v1.70.2]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> utf8parse_v0_2_2[utf8parse v0.2.2]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> clap_lex_v0_7_6[clap_lex v0.7.6]
    clap_builder_v4_5_53[clap_builder v4.5.53] --> strsim_v0_11_1[strsim v0.11.1]
    axconfig_gen_v0_2_0[axconfig-gen v0.2.0] --> heck_v0_5_0[heck v0.5.0]
    axconfig_gen_v0_2_0[axconfig-gen v0.2.0] --> equivalent_v1_0_2[equivalent v1.0.2]
    axconfig_gen_v0_2_0[axconfig-gen v0.2.0] --> toml_datetime_v0_6_11[toml_datetime v0.6.11]
    axconfig_gen_v0_2_0[axconfig-gen v0.2.0] --> toml_write_v0_1_2[toml_write v0.1.2]
    axconfig_gen_v0_2_0[axconfig-gen v0.2.0] --> winnow_v0_7_14[winnow v0.7.14]
    axdriver_v0_2_0[axdriver v0.2.0] --> axdriver_base_v0_1_2[axdriver_base v0.1.2]
    axdriver_v0_2_0[axdriver v0.2.0] --> axdriver_block_v0_1_2[axdriver_block v0.1.2]
    axdriver_block_v0_1_2[axdriver_block v0.1.2] --> axdriver_base_v0_1_2[axdriver_base v0.1.2]
    axdriver_v0_2_0[axdriver v0.2.0] --> axdriver_display_v0_1_2[axdriver_display v0.1.2]
    axdriver_display_v0_1_2[axdriver_display v0.1.2] --> axdriver_base_v0_1_2[axdriver_base v0.1.2]
    axdriver_v0_2_0[axdriver v0.2.0] --> axdriver_net_v0_1_2[axdriver_net v0.1.2]
    axdriver_net_v0_1_2[axdriver_net v0.1.2] --> axdriver_base_v0_1_2[axdriver_base v0.1.2]
    axdriver_net_v0_1_2[axdriver_net v0.1.2] --> spin_v0_9_8[spin v0.9.8]
    spin_v0_9_8[spin v0.9.8] --> lock_api_v0_4_14[lock_api v0.4.14]
    lock_api_v0_4_14[lock_api v0.4.14] --> scopeguard_v1_2_0[scopeguard v1.2.0]
    axdriver_v0_2_0[axdriver v0.2.0] --> axdriver_pci_v0_1_2[axdriver_pci v0.1.2]
    axdriver_pci_v0_1_2[axdriver_pci v0.1.2] --> virtio_drivers_v0_7_5[virtio-drivers v0.7.5]
    virtio_drivers_v0_7_5[virtio-drivers v0.7.5] --> byteorder_v1_5_0[byteorder v1.5.0]
    virtio_drivers_v0_7_5[virtio-drivers v0.7.5] --> zerocopy_derive_v0_7_35[zerocopy-derive v0.7.35]
    axdriver_v0_2_0[axdriver v0.2.0] --> axdriver_virtio_v0_1_2[axdriver_virtio v0.1.2]
    axdriver_virtio_v0_1_2[axdriver_virtio v0.1.2] --> axdriver_base_v0_1_2[axdriver_base v0.1.2]
    axdriver_virtio_v0_1_2[axdriver_virtio v0.1.2] --> axdriver_block_v0_1_2[axdriver_block v0.1.2]
    axdriver_virtio_v0_1_2[axdriver_virtio v0.1.2] --> axdriver_net_v0_1_2[axdriver_net v0.1.2]
    axdriver_virtio_v0_1_2[axdriver_virtio v0.1.2] --> virtio_drivers_v0_7_5[virtio-drivers v0.7.5]
    axdriver_v0_2_0[axdriver v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axhal_v0_2_0[axhal v0.2.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    axhal_v0_2_0[axhal v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axhal_v0_2_0[axhal v0.2.0] --> axcpu_v0_3_0[axcpu v0.3.0]
    axcpu_v0_3_0[axcpu v0.3.0] --> axbacktrace_v0_1_1[axbacktrace v0.1.1]
    axbacktrace_v0_1_1[axbacktrace v0.1.1] --> spin_v0_10_0[spin v0.10.0]
    spin_v0_10_0[spin v0.10.0] --> lock_api_v0_4_14[lock_api v0.4.14]
    axcpu_v0_3_0[axcpu v0.3.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    axcpu_v0_3_0[axcpu v0.3.0] --> linkme_impl_v0_3_35[linkme-impl v0.3.35]
    axcpu_v0_3_0[axcpu v0.3.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axcpu_v0_3_0[axcpu v0.3.0] --> page_table_entry_v0_5_7[page_table_entry v0.5.7]
    page_table_entry_v0_5_7[page_table_entry v0.5.7] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    page_table_entry_v0_5_7[page_table_entry v0.5.7] --> bit_field_v0_10_3[bit_field v0.10.3]
    page_table_entry_v0_5_7[page_table_entry v0.5.7] --> const_fn_v0_4_11[const_fn v0.4.11]
    page_table_entry_v0_5_7[page_table_entry v0.5.7] --> volatile_v0_4_6[volatile v0.4.6]
    axcpu_v0_3_0[axcpu v0.3.0] --> percpu_v0_2_0[percpu v0.2.0]
    percpu_v0_2_0[percpu v0.2.0] --> kernel_guard_v0_1_3[kernel_guard v0.1.3]
    percpu_v0_2_0[percpu v0.2.0] --> percpu_macros_v0_2_0[percpu_macros v0.2.0]
    percpu_v0_2_0[percpu v0.2.0] --> spin_v0_9_8[spin v0.9.8]
    percpu_v0_2_0[percpu v0.2.0] --> bit_field_v0_10_3[bit_field v0.10.3]
    percpu_v0_2_0[percpu v0.2.0] --> raw_cpuid_v10_7_0[raw-cpuid v10.7.0]
    axhal_v0_2_0[axhal v0.2.0] --> axplat_v0_3_0[axplat v0.3.0]
    axplat_v0_3_0[axplat v0.3.0] --> axplat_macros_v0_1_0[axplat-macros v0.1.0]
    axplat_v0_3_0[axplat v0.3.0] --> const_str_v0_6_4[const-str v0.6.4]
    axplat_v0_3_0[axplat v0.3.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axplat_v0_3_0[axplat v0.3.0] --> handler_table_v0_1_2[handler_table v0.1.2]
    axplat_v0_3_0[axplat v0.3.0] --> kspin_v0_1_1[kspin v0.1.1]
    axplat_v0_3_0[axplat v0.3.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axplat_v0_3_0[axplat v0.3.0] --> percpu_v0_2_0[percpu v0.2.0]
    axhal_v0_2_0[axhal v0.2.0] --> fdt_parser_v0_4_18[fdt-parser v0.4.18]
    axhal_v0_2_0[axhal v0.2.0] --> hash32_v0_3_1[hash32 v0.3.1]
    hash32_v0_3_1[hash32 v0.3.1] --> byteorder_v1_5_0[byteorder v1.5.0]
    axhal_v0_2_0[axhal v0.2.0] --> stable_deref_trait_v1_2_1[stable_deref_trait v1.2.1]
    axhal_v0_2_0[axhal v0.2.0] --> kernel_guard_v0_1_3[kernel_guard v0.1.3]
    axhal_v0_2_0[axhal v0.2.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    axhal_v0_2_0[axhal v0.2.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axhal_v0_2_0[axhal v0.2.0] --> page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7]
    page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7] --> arrayvec_v0_7_6[arrayvec v0.7.6]
    page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7] --> axerrno_v0_1_2[axerrno v0.1.2]
    page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7] --> bitmaps_v3_2_1[bitmaps v3.2.1]
    page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7] --> page_table_entry_v0_5_7[page_table_entry v0.5.7]
    axhal_v0_2_0[axhal v0.2.0] --> percpu_v0_2_0[percpu v0.2.0]
    axdriver_v0_2_0[axdriver v0.2.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axdriver_v0_2_0[axdriver v0.2.0] --> smallvec_v1_15_1[smallvec v1.15.1]
    starry_v0_1_0[starry v0.1.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    starry_v0_1_0[starry v0.1.0] --> axfeat_v0_2_0[axfeat v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axbacktrace_v0_1_1[axbacktrace v0.1.1]
    axfeat_v0_2_0[axfeat v0.2.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axfs_v0_2_0[axfs v0.2.0]
    axfs_v0_2_0[axfs v0.2.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    axfs_v0_2_0[axfs v0.2.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    axfs_v0_2_0[axfs v0.2.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    axfs_v0_2_0[axfs v0.2.0] --> axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> axpoll_v0_1_0[axpoll v0.1.0]
    axpoll_v0_1_0[axpoll v0.1.0] --> linux_raw_sys_v0_11_0[linux-raw-sys v0.11.0]
    axpoll_v0_1_0[axpoll v0.1.0] --> spin_v0_10_0[spin v0.10.0]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> allocator_api2_v0_2_21[allocator-api2 v0.2.21]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> equivalent_v1_0_2[equivalent v1.0.2]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> foldhash_v0_1_5[foldhash v0.1.5]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> inherit_methods_macro_v0_1_0[inherit-methods-macro v0.1.0]
    inherit_methods_macro_v0_1_0[inherit-methods-macro v0.1.0] --> fnv_v1_0_7[fnv v1.0.7]
    inherit_methods_macro_v0_1_0[inherit-methods-macro v0.1.0] --> ident_case_v1_0_1[ident_case v1.0.1]
    inherit_methods_macro_v0_1_0[inherit-methods-macro v0.1.0] --> strsim_v0_10_0[strsim v0.10.0]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> smallvec_v1_15_1[smallvec v1.15.1]
    axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0] --> spin_v0_10_0[spin v0.10.0]
    axfs_v0_2_0[axfs v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axfs_v0_2_0[axfs v0.2.0] --> axio_v0_3_0_pre_1[axio v0.3.0-pre.1]
    axio_v0_3_0_pre_1[axio v0.3.0-pre.1] --> axerrno_v0_2_2[axerrno v0.2.2]
    axio_v0_3_0_pre_1[axio v0.3.0-pre.1] --> autocfg_v1_5_0[autocfg v1.5.0]
    axfs_v0_2_0[axfs v0.2.0] --> axpoll_v0_1_0[axpoll v0.1.0]
    axfs_v0_2_0[axfs v0.2.0] --> axsync_v0_2_0[axsync v0.2.0]
    axsync_v0_2_0[axsync v0.2.0] --> axtask_v0_2_0[axtask v0.2.0]
    axtask_v0_2_0[axtask v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axtask_v0_2_0[axtask v0.2.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    axtask_v0_2_0[axtask v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axtask_v0_2_0[axtask v0.2.0] --> axpoll_v0_1_0[axpoll v0.1.0]
    axtask_v0_2_0[axtask v0.2.0] --> axsched_v0_3_1[axsched v0.3.1]
    axsched_v0_3_1[axsched v0.3.1] --> linked_list_r4l_v0_3_0[linked_list_r4l v0.3.0]
    axtask_v0_2_0[axtask v0.2.0] --> bitmaps_v3_2_1[bitmaps v3.2.1]
    axtask_v0_2_0[axtask v0.2.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axtask_v0_2_0[axtask v0.2.0] --> concurrent_queue_v2_5_0[concurrent-queue v2.5.0]
    concurrent_queue_v2_5_0[concurrent-queue v2.5.0] --> crossbeam_utils_v0_8_21[crossbeam-utils v0.8.21]
    axtask_v0_2_0[axtask v0.2.0] --> pin_project_lite_v0_2_16[pin-project-lite v0.2.16]
    axtask_v0_2_0[axtask v0.2.0] --> extern_trait_v0_2_0[extern-trait v0.2.0]
    axtask_v0_2_0[axtask v0.2.0] --> futures_core_v0_3_31[futures-core v0.3.31]
    axtask_v0_2_0[axtask v0.2.0] --> futures_macro_v0_3_31[futures-macro v0.3.31]
    axtask_v0_2_0[axtask v0.2.0] --> futures_task_v0_3_31[futures-task v0.3.31]
    axtask_v0_2_0[axtask v0.2.0] --> pin_utils_v0_1_0[pin-utils v0.1.0]
    axtask_v0_2_0[axtask v0.2.0] --> kernel_guard_v0_1_3[kernel_guard v0.1.3]
    axtask_v0_2_0[axtask v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    axtask_v0_2_0[axtask v0.2.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    axtask_v0_2_0[axtask v0.2.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axtask_v0_2_0[axtask v0.2.0] --> percpu_v0_2_0[percpu v0.2.0]
    axsync_v0_2_0[axsync v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    axsync_v0_2_0[axsync v0.2.0] --> lock_api_v0_4_14[lock_api v0.4.14]
    axfs_v0_2_0[axfs v0.2.0] --> num_traits_v0_2_19[num-traits v0.2.19]
    num_traits_v0_2_19[num-traits v0.2.19] --> autocfg_v1_5_0[autocfg v1.5.0]
    axfs_v0_2_0[axfs v0.2.0] --> intrusive_collections_v0_9_7[intrusive-collections v0.9.7]
    intrusive_collections_v0_9_7[intrusive-collections v0.9.7] --> memoffset_v0_9_1[memoffset v0.9.1]
    memoffset_v0_9_1[memoffset v0.9.1] --> autocfg_v1_5_0[autocfg v1.5.0]
    axfs_v0_2_0[axfs v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    axfs_v0_2_0[axfs v0.2.0] --> allocator_api2_v0_2_21[allocator-api2 v0.2.21]
    axfs_v0_2_0[axfs v0.2.0] --> equivalent_v1_0_2[equivalent v1.0.2]
    axfs_v0_2_0[axfs v0.2.0] --> foldhash_v0_2_0[foldhash v0.2.0]
    axfs_v0_2_0[axfs v0.2.0] --> lwext4_rust_v0_2_0[lwext4_rust v0.2.0]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> minimal_lexical_v0_2_1[minimal-lexical v0.2.1]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> libloading_v0_8_9[libloading v0.8.9]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> either_v1_15_0[either v1.15.0]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> regex_automata_v0_4_13[regex-automata v0.4.13]
    regex_automata_v0_4_13[regex-automata v0.4.13] --> regex_syntax_v0_8_8[regex-syntax v0.8.8]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> regex_syntax_v0_8_8[regex-syntax v0.8.8]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> rustc_hash_v2_1_1[rustc-hash v2.1.1]
    lwext4_rust_v0_2_0[lwext4_rust v0.2.0] --> shlex_v1_3_0[shlex v1.3.0]
    axfs_v0_2_0[axfs v0.2.0] --> scope_local_v0_1_0[scope-local v0.1.0]
    scope_local_v0_1_0[scope-local v0.1.0] --> percpu_v0_2_0[percpu v0.2.0]
    scope_local_v0_1_0[scope-local v0.1.0] --> spin_v0_9_8[spin v0.9.8]
    axfs_v0_2_0[axfs v0.2.0] --> slab_v0_4_11[slab v0.4.11]
    axfs_v0_2_0[axfs v0.2.0] --> spin_v0_10_0[spin v0.10.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axlog_v0_2_0[axlog v0.2.0]
    axlog_v0_2_0[axlog v0.2.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axlog_v0_2_0[axlog v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    axfeat_v0_2_0[axfeat v0.2.0] --> axnet_v0_2_0[axnet v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> concurrent_queue_v2_5_0[concurrent-queue v2.5.0]
    axnet_v0_2_0[axnet v0.2.0] --> event_listener_strategy_v0_5_4[event-listener-strategy v0.5.4]
    event_listener_strategy_v0_5_4[event-listener-strategy v0.5.4] --> pin_project_lite_v0_2_16[pin-project-lite v0.2.16]
    axnet_v0_2_0[axnet v0.2.0] --> futures_core_v0_3_31[futures-core v0.3.31]
    axnet_v0_2_0[axnet v0.2.0] --> pin_project_lite_v0_2_16[pin-project-lite v0.2.16]
    axnet_v0_2_0[axnet v0.2.0] --> async_trait_v0_1_89[async-trait v0.1.89]
    axnet_v0_2_0[axnet v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    axnet_v0_2_0[axnet v0.2.0] --> axfs_v0_2_0[axfs v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0]
    axnet_v0_2_0[axnet v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> axio_v0_3_0_pre_1[axio v0.3.0-pre.1]
    axnet_v0_2_0[axnet v0.2.0] --> axpoll_v0_1_0[axpoll v0.1.0]
    axnet_v0_2_0[axnet v0.2.0] --> axsync_v0_2_0[axsync v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> axtask_v0_2_0[axtask v0.2.0]
    axnet_v0_2_0[axnet v0.2.0] --> spin_v0_9_8[spin v0.9.8]
    axnet_v0_2_0[axnet v0.2.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    axnet_v0_2_0[axnet v0.2.0] --> crossbeam_utils_v0_8_21[crossbeam-utils v0.8.21]
    axnet_v0_2_0[axnet v0.2.0] --> smoltcp_v0_12_0[smoltcp v0.12.0]
    smoltcp_v0_12_0[smoltcp v0.12.0] --> byteorder_v1_5_0[byteorder v1.5.0]
    smoltcp_v0_12_0[smoltcp v0.12.0] --> hash32_v0_3_1[hash32 v0.3.1]
    smoltcp_v0_12_0[smoltcp v0.12.0] --> stable_deref_trait_v1_2_1[stable_deref_trait v1.2.1]
    smoltcp_v0_12_0[smoltcp v0.12.0] --> managed_v0_8_0[managed v0.8.0]
    axnet_v0_2_0[axnet v0.2.0] --> spin_v0_10_0[spin v0.10.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axruntime_v0_2_0[axruntime v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axbacktrace_v0_1_1[axbacktrace v0.1.1]
    axruntime_v0_2_0[axruntime v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axfs_v0_2_0[axfs v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axlog_v0_2_0[axlog v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axmm_v0_2_0[axmm v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    axmm_v0_2_0[axmm v0.2.0] --> axfs_v0_2_0[axfs v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0]
    axmm_v0_2_0[axmm v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> axsync_v0_2_0[axsync v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> axtask_v0_2_0[axtask v0.2.0]
    axmm_v0_2_0[axmm v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    axmm_v0_2_0[axmm v0.2.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    axmm_v0_2_0[axmm v0.2.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axmm_v0_2_0[axmm v0.2.0] --> memory_set_v0_4_1[memory_set v0.4.1]
    memory_set_v0_4_1[memory_set v0.4.1] --> axerrno_v0_1_2[axerrno v0.1.2]
    memory_set_v0_4_1[memory_set v0.4.1] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    axmm_v0_2_0[axmm v0.2.0] --> page_table_multiarch_v0_5_7[page_table_multiarch v0.5.7]
    axruntime_v0_2_0[axruntime v0.2.0] --> axnet_v0_2_0[axnet v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axplat_v0_3_0[axplat v0.3.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axtask_v0_2_0[axtask v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axruntime_v0_2_0[axruntime v0.2.0] --> percpu_v0_2_0[percpu v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axsync_v0_2_0[axsync v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axtask_v0_2_0[axtask v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> axfs_v0_2_0[axfs v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> axhal_v0_2_0[axhal v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> axlog_v0_2_0[axlog v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> axruntime_v0_2_0[axruntime v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> axsync_v0_2_0[axsync v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> axtask_v0_2_0[axtask v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> linux_raw_sys_v0_11_0[linux-raw-sys v0.11.0]
    starry_v0_1_0[starry v0.1.0] --> starry_api_v0_1_0[starry-api v0.1.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axalloc_v0_2_0[axalloc v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axbacktrace_v0_1_1[axbacktrace v0.1.1]
    starry_api_v0_1_0[starry-api v0.1.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axdisplay_v0_2_0[axdisplay v0.2.0]
    axdisplay_v0_2_0[axdisplay v0.2.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    axdisplay_v0_2_0[axdisplay v0.2.0] --> axsync_v0_2_0[axsync v0.2.0]
    axdisplay_v0_2_0[axdisplay v0.2.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    starry_api_v0_1_0[starry-api v0.1.0] --> axdriver_v0_2_0[axdriver v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    starry_api_v0_1_0[starry-api v0.1.0] --> axfeat_v0_2_0[axfeat v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axfs_v0_2_0[axfs v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axhal_v0_2_0[axhal v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axio_v0_3_0_pre_1[axio v0.3.0-pre.1]
    starry_api_v0_1_0[starry-api v0.1.0] --> axlog_v0_2_0[axlog v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axmm_v0_2_0[axmm v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axnet_v0_2_0[axnet v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axpoll_v0_1_0[axpoll v0.1.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axsync_v0_2_0[axsync v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> axtask_v0_2_0[axtask v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> bitmaps_v3_2_1[bitmaps v3.2.1]
    starry_api_v0_1_0[starry-api v0.1.0] --> bytemuck_derive_v1_10_2[bytemuck_derive v1.10.2]
    starry_api_v0_1_0[starry-api v0.1.0] --> downcast_rs_v2_0_2[downcast-rs v2.0.2]
    starry_api_v0_1_0[starry-api v0.1.0] --> flatten_objects_v0_2_4[flatten_objects v0.2.4]
    flatten_objects_v0_2_4[flatten_objects v0.2.4] --> bitmaps_v3_2_1[bitmaps v3.2.1]
    starry_api_v0_1_0[starry-api v0.1.0] --> inherit_methods_macro_v0_1_0[inherit-methods-macro v0.1.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> kspin_v0_1_1[kspin v0.1.1]
    starry_api_v0_1_0[starry-api v0.1.0] --> linux_raw_sys_v0_11_0[linux-raw-sys v0.11.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    starry_api_v0_1_0[starry-api v0.1.0] --> num_enum_derive_v0_7_5[num_enum_derive v0.7.5]
    starry_api_v0_1_0[starry-api v0.1.0] --> rand_core_v0_9_3[rand_core v0.9.3]
    starry_api_v0_1_0[starry-api v0.1.0] --> scope_local_v0_1_0[scope-local v0.1.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> slab_v0_4_11[slab v0.4.11]
    starry_api_v0_1_0[starry-api v0.1.0] --> spin_v0_10_0[spin v0.10.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> starry_core_v0_1_0[starry-core v0.1.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axbacktrace_v0_1_1[axbacktrace v0.1.1]
    starry_core_v0_1_0[starry-core v0.1.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    starry_core_v0_1_0[starry-core v0.1.0] --> axfeat_v0_2_0[axfeat v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axfs_v0_2_0[axfs v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axfs_ng_vfs_v0_1_0[axfs-ng-vfs v0.1.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axhal_v0_2_0[axhal v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axio_v0_3_0_pre_1[axio v0.3.0-pre.1]
    starry_core_v0_1_0[starry-core v0.1.0] --> axlog_v0_2_0[axlog v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axmm_v0_2_0[axmm v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axpoll_v0_1_0[axpoll v0.1.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axsync_v0_2_0[axsync v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> axtask_v0_2_0[axtask v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> extern_trait_v0_2_0[extern-trait v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> inherit_methods_macro_v0_1_0[inherit-methods-macro v0.1.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> kernel_elf_parser_v0_3_3[kernel-elf-parser v0.3.3]
    kernel_elf_parser_v0_3_3[kernel-elf-parser v0.3.3] --> zero_v0_1_3[zero v0.1.3]
    kernel_elf_parser_v0_3_3[kernel-elf-parser v0.3.3] --> zerocopy_derive_v0_8_31[zerocopy-derive v0.8.31]
    starry_core_v0_1_0[starry-core v0.1.0] --> kernel_guard_v0_1_3[kernel_guard v0.1.3]
    starry_core_v0_1_0[starry-core v0.1.0] --> kspin_v0_1_1[kspin v0.1.1]
    starry_core_v0_1_0[starry-core v0.1.0] --> linux_raw_sys_v0_11_0[linux-raw-sys v0.11.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> lock_api_v0_4_14[lock_api v0.4.14]
    starry_core_v0_1_0[starry-core v0.1.0] --> memory_addr_v0_4_1[memory_addr v0.4.1]
    starry_core_v0_1_0[starry-core v0.1.0] --> aliasable_v0_1_3[aliasable v0.1.3]
    starry_core_v0_1_0[starry-core v0.1.0] --> heck_v0_4_1[heck v0.4.1]
    starry_core_v0_1_0[starry-core v0.1.0] --> yansi_v1_0_1[yansi v1.0.1]
    starry_core_v0_1_0[starry-core v0.1.0] --> percpu_v0_2_0[percpu v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> scope_local_v0_1_0[scope-local v0.1.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> slab_v0_4_11[slab v0.4.11]
    starry_core_v0_1_0[starry-core v0.1.0] --> spin_v0_10_0[spin v0.10.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> starry_process_v0_2_0[starry-process v0.2.0]
    starry_process_v0_2_0[starry-process v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    starry_process_v0_2_0[starry-process v0.2.0] --> lazyinit_v0_2_2[lazyinit v0.2.2]
    starry_process_v0_2_0[starry-process v0.2.0] --> weak_map_v0_1_2[weak-map v0.1.2]
    starry_core_v0_1_0[starry-core v0.1.0] --> starry_signal_v0_2_3[starry-signal v0.2.3]
    starry_signal_v0_2_3[starry-signal v0.2.3] --> axcpu_v0_3_0[axcpu v0.3.0]
    starry_signal_v0_2_3[starry-signal v0.2.3] --> convert_case_v0_10_0[convert_case v0.10.0]
    convert_case_v0_10_0[convert_case v0.10.0] --> unicode_segmentation_v1_12_0[unicode-segmentation v1.12.0]
    starry_signal_v0_2_3[starry-signal v0.2.3] --> unicode_xid_v0_2_6[unicode-xid v0.2.6]
    starry_signal_v0_2_3[starry-signal v0.2.3] --> kspin_v0_1_1[kspin v0.1.1]
    starry_signal_v0_2_3[starry-signal v0.2.3] --> linux_raw_sys_v0_11_0[linux-raw-sys v0.11.0]
    starry_signal_v0_2_3[starry-signal v0.2.3] --> starry_vm_v0_2_0[starry-vm v0.2.0]
    starry_vm_v0_2_0[starry-vm v0.2.0] --> axerrno_v0_2_2[axerrno v0.2.2]
    starry_vm_v0_2_0[starry-vm v0.2.0] --> extern_trait_v0_2_0[extern-trait v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> starry_vm_v0_2_0[starry-vm v0.2.0]
    starry_core_v0_1_0[starry-core v0.1.0] --> uluru_v3_1_0[uluru v3.1.0]
    uluru_v3_1_0[uluru v3.1.0] --> arrayvec_v0_7_6[arrayvec v0.7.6]
    starry_core_v0_1_0[starry-core v0.1.0] --> weak_map_v0_1_2[weak-map v0.1.2]
    starry_api_v0_1_0[starry-api v0.1.0] --> starry_process_v0_2_0[starry-process v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> starry_signal_v0_2_3[starry-signal v0.2.3]
    starry_api_v0_1_0[starry-api v0.1.0] --> starry_vm_v0_2_0[starry-vm v0.2.0]
    starry_api_v0_1_0[starry-api v0.1.0] --> syscalls_v0_7_0[syscalls v0.7.0]
    starry_v0_1_0[starry v0.1.0] --> starry_core_v0_1_0[starry-core v0.1.0]
    starry_v0_1_0[starry v0.1.0] --> starry_process_v0_2_0[starry-process v0.2.0]
    starry_v0_1_0[starry v0.1.0] --> starry_signal_v0_2_3[starry-signal v0.2.3]
