graph TD
    ch8_v0_0_1[ch8 v0.0.1] --> easy_fs_v0_1_0[easy-fs v0.1.0]
    ch8_v0_0_1[ch8 v0.0.1] --> kernel_alloc_v0_1_0[kernel-alloc v0.1.0]
    kernel_alloc_v0_1_0[kernel-alloc v0.1.0] --> customizable_buddy_v0_0_3[customizable-buddy v0.0.3]
    kernel_alloc_v0_1_0[kernel-alloc v0.1.0] --> page_table_v0_0_6[page-table v0.0.6]
    ch8_v0_0_1[ch8 v0.0.1] --> kernel_context_v0_1_0[kernel-context v0.1.0]
    ch8_v0_0_1[ch8 v0.0.1] --> kernel_vm_v0_1_0[kernel-vm v0.1.0]
    kernel_vm_v0_1_0[kernel-vm v0.1.0] --> page_table_v0_0_6[page-table v0.0.6]
    ch8_v0_0_1[ch8 v0.0.1] --> linker_v0_0_1[linker v0.0.1]
    ch8_v0_0_1[ch8 v0.0.1] --> rcore_console_v0_0_0[rcore-console v0.0.0]
    ch8_v0_0_1[ch8 v0.0.1] --> rcore_task_manage_v0_0_0[rcore-task-manage v0.0.0]
    ch8_v0_0_1[ch8 v0.0.1] --> signal_v0_1_0[signal v0.1.0]
    signal_v0_1_0[signal v0.1.0] --> kernel_context_v0_1_0[kernel-context v0.1.0]
    signal_v0_1_0[signal v0.1.0] --> signal_defs_v0_1_0[signal-defs v0.1.0]
    ch8_v0_0_1[ch8 v0.0.1] --> signal_impl_v0_1_0[signal-impl v0.1.0]
    signal_impl_v0_1_0[signal-impl v0.1.0] --> kernel_context_v0_1_0[kernel-context v0.1.0]
    signal_impl_v0_1_0[signal-impl v0.1.0] --> signal_v0_1_0[signal v0.1.0]
    ch8_v0_0_1[ch8 v0.0.1] --> sync_v0_1_0[sync v0.1.0]
    sync_v0_1_0[sync v0.1.0] --> rcore_task_manage_v0_0_0[rcore-task-manage v0.0.0]
    ch8_v0_0_1[ch8 v0.0.1] --> syscall_v0_1_0[syscall v0.1.0]
    syscall_v0_1_0[syscall v0.1.0] --> signal_defs_v0_1_0[signal-defs v0.1.0]
    ch8_v0_0_1[ch8 v0.0.1] --> virtio_drivers_v0_1_0[virtio-drivers v0.1.0]
